# 1.1 生成Numpy数组

* 从已有数据生成

In [2]:
import numpy as np

# 列表转换成ndarray:
lst1 = [1,2,3,4]
nd1 = np.array(lst1)

print(nd1)
print(type(nd1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# 嵌套列表可以转换成多维ndarray：
lst2 = [[3.14, 2.17, 0, 1, 2], [1, 2, 3, 4, 5]]

nd2 = np.array(lst2)

print(nd2)
print(type(nd2))

[[3.14 2.17 0.   1.   2.  ]
 [1.   2.   3.   4.   5.  ]]
<class 'numpy.ndarray'>


* 使用numpy模块生成numpy数组

<img src="Screenshot from 2021-02-21 14-23-40.png">

In [7]:
# 具体使用：

nd3 = np.random.random([3,3])
print(nd3)
print(nd3.shape)

[[0.34601926 0.76659052 0.67391318]
 [0.44137326 0.42160211 0.35862429]
 [0.01046353 0.31657078 0.49442139]]
(3, 3)


In [8]:
# 为了每次生成同一份数据，可以指定一个随机种子:
# 用shuffle函数打乱生成的随机数

np.random.seed(123)
nd4 = np.random.randn(2,3)
print(nd4)

np.random.shuffle(nd4)
print("打乱后：")
print(nd4)
print(type(nd4))

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
打乱后：
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]
<class 'numpy.ndarray'>


* 创建特定形状的多维数组

<img src="Screenshot from 2021-02-21 14-35-52.png">

In [10]:
# 生成全是 0 的 3x3 矩阵
nd5 =np.zeros([3, 3])

# 生成与nd5形状一样的全0矩阵
np.zeros_like(nd5)

# 生成全是 1 的 3x3 矩阵
nd6 = np.ones([3, 3])

# 生成 3 阶的单位矩阵
nd7 = np.eye(3)

# 生成 3 阶对角矩阵
nd8 = np.diag([1, 2, 3])

print(nd5)
print(nd6)
print(nd7)
print(nd8)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
# 把生成的数据暂时保存起来

nd9 =np.random.random([5, 5])
np.savetxt(X=nd9, fname='./test1.txt')
nd10 = np.loadtxt('./test1.txt')
print(nd10)

[[0.41092437 0.5796943  0.13995076 0.40101756 0.62731701]
 [0.32415089 0.24475928 0.69475518 0.5939024  0.63179202]
 [0.44025718 0.08372648 0.71233018 0.42786349 0.2977805 ]
 [0.49208478 0.74029639 0.35772892 0.41720995 0.65472131]
 [0.37380143 0.23451288 0.98799529 0.76599595 0.77700444]]


* 利用arange、linspace函数生成数组

In [13]:
# np.arange([start,] stop[,step,], dtype=None)
# 其中start与stop用来指定范围，step用来设定步长。在生成一个ndarray时，start默认为0，步长step可为小数。
print(np.arange(10))

print(np.arange(0, 10))

print(np.arange(1, 4, 0.5))

print(np.arange(9, -1, -1))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5]
[9 8 7 6 5 4 3 2 1 0]


In [15]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# linspace可以根据输入的指定数据范围以及等份数量，自动生成一个线性等分向量
# 如果将retstep设置为True，则会返回一个带步长的ndarray

print(np.linspace(0, 1, 10))

print(np.linspace(0, 1, 10, retstep=True))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]), 0.1111111111111111)


# 1.2 获取元素

* 获取数据的方法

In [35]:
np.random.seed(2019)
nd11 = np.random.random([10]) # 有没有方括号都一样，type = numpy.ndarray

# 获取指定位置的数据，获取第4个元素
nd11[3]

# 截取一段数据
nd11[3:6]

# 截取固定间隔数据
nd11[1:6:2]

# 倒序取数
nd11[::-2]

array([0.4057498 , 0.90320616, 0.29917202, 0.6378774 , 0.39308051])

In [36]:
# 1-2行，1-2列
nd12 = np.arange(25).reshape([5,5])
nd12[1:3,1:3]

# 截取一个多维数组中，数值在一个值域之内的数据
# nd12[(nd12>3)&(nd12<10)]

# 1-2行
# nd12[[1,2]] #或nd12[1:3,:]

# 所有行的1-3列
# nd12[:,1:3]

array([[ 6,  7],
       [11, 12]])

In [38]:
# 通过random.choice函数从指定的样本中随机抽取数据

from numpy import random as nr

a = np.arange(1,25,dtype=float)
c1 = nr.choice(a,size=(3,4)) #size指定输出数组形状
c2 = nr.choice(a,size=(3,4),replace=False) #replace缺省为True，即可重复抽取。
#下式中参数p指定每个元素对应的抽取概率，缺省为每个元素被抽取的概率相同。
c3 = nr.choice(a,size=(3,4),p=a / np.sum(a))
print("随机可重复抽取")
print(c1)
print("随机但不重复抽取")
print(c2)
print("随机但按制度概率抽取")
print(c3)

随机可重复抽取
[[16. 15. 18. 18.]
 [14. 18. 18. 14.]
 [23. 16. 13.  3.]]
随机但不重复抽取
[[ 6. 14.  7.  4.]
 [19.  2.  3. 16.]
 [12. 10.  9. 20.]]
随机但按制度概率抽取
[[24. 15. 23. 16.]
 [ 9.  9. 17. 19.]
 [23. 13. 12. 17.]]


# 1.3 Numpy的算术运算

* 逐元乘法（Element-Wise Product），运算符为np.multiply(),或*

In [39]:
# np.numpy.multiply(x1, x2, /, out=None, *, where=True,casting='same_kind', order='K', dtype=None,
#     numpy.multiply(x1, x2, /, out=None, *, where=True,casting='same_kind', order='K', 
#     dtype=None, subok=True[, signature, extobj])
# 
# np.multiply函数用于数组或矩阵对应元素相乘，输出与相乘数组或矩阵的大小一致

# eg:

A = np.array([[1, 2], [-1, 4]])
B = np.array([[2, 0], [3, 4]])
A*B

array([[ 2,  0],
       [-3, 16]])

In [40]:
# 还可以和单一数值（或称为标量）进行运算。
print(A*2.0)
print(A/2.0)

[[ 2.  4.]
 [-2.  8.]]
[[ 0.5  1. ]
 [-0.5  2. ]]


In [41]:
# 推而广之，数组通过一些激活函数后，输出与输入形状一致

X = np.random.rand(2,3)

def softmoid(x):
    return 1/(1+np.exp(-x))

def relu(x):
    return np.maximum(0,x)

def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

print("输入参数X的形状：",X.shape)
print("激活函数softmoid输出形状：",softmoid(X).shape)
print("激活函数relu输出形状：",relu(X).shape)
print("激活函数softmax输出形状：",softmax(X).shape)

输入参数X的形状： (2, 3)
激活函数softmoid输出形状： (2, 3)
激活函数relu输出形状： (2, 3)
激活函数softmax输出形状： (2, 3)


* 点积或内积元素，运算符为np.dot()

In [42]:
# numpy.dot(a, b, out=None)

X1 = np.array([[1,2],[3,4]])
X2 = np.array([[5,6,7],[8,9,10]])
X3 = np.dot(X1,X2)

print(X3)

[[21 24 27]
 [47 54 61]]


# 1.4 数组变形

* 更改数组的形状

In [48]:
# reshape

arr = np.arange(10)
print(arr)

# 将向量 arr 维度变换为2行5列
print(arr.reshape(2, 5))

# 指定维度时可以只指定行数或列数, 其他用 -1 代替
print(arr.reshape(5, -1))
print(arr.reshape(-1, 5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [46]:
# resize，与reshape有点值传递和址传递的意思

arr =np.arange(10)
print(arr)

# 将向量 arr 维度变换为2行5列
arr.resize(2, 5)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [49]:
# T
arr = np.arange(12).reshape(3,4)

# 向量 arr 为3行4列
print(arr)

# 将向量 arr 进行转置为4行3列
print(arr.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [50]:
# ravel，向量展平

arr =np.arange(6).reshape(2, -1)
print(arr)

print("按照列优先，展平")
print(arr.ravel('F'))

print("按照行优先，展平")
print(arr.ravel())

[[0 1 2]
 [3 4 5]]
按照列优先，展平
[0 3 1 4 2 5]
按照行优先，展平
[0 1 2 3 4 5]


In [51]:
# flatten，把矩阵转换为向量，这种需求经常出现在卷积网络与全连接层之间

a = np.floor(10*np.random.random((3,4)))  # np.floor()：返回不大于输入参数的最大整数（向下取整）
print(a)
print(a.flatten())

[[4. 4. 3. 3.]
 [2. 3. 5. 1.]
 [7. 5. 1. 9.]]
[4. 4. 3. 3. 2. 3. 5. 1. 7. 5. 1. 9.]


In [53]:
# squeeze
# 这是一个主要用来降维的函数，把矩阵中含1的维度去掉。在PyTorch中还有一种与之相反的操作——torch.unsqueeze

arr = np.arange(3).reshape(3, 1)

print(arr.shape) #(3,1)
print(arr.squeeze())
print(arr.squeeze().shape) #(3,)

arr1 =np.arange(6).reshape(3,1,2,1)

print(arr1.shape) #(3, 1, 2, 1)
print(arr1.squeeze())
print(arr1.squeeze().shape) #(3, 2)

(3, 1)
[0 1 2]
(3,)
(3, 1, 2, 1)
[[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [54]:
# transpose 
# 对高维矩阵进行轴对换，这个在深度学习中经常使用，比如把图片中表示颜色顺序的RGB改为GBR

arr2 = np.arange(24).reshape(2,3,4)
print(arr2.shape) #(2, 3, 4)
print(arr2.transpose(1,2,0).shape) #(3, 4, 2)

(2, 3, 4)
(3, 4, 2)


* 合并数组

In [55]:
# append:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.append(a, b)
print(c)

[1 2 3 4 5 6]


In [56]:
# 合并多维数组

a = np.arange(4).reshape(2, 2)
b = np.arange(4).reshape(2, 2)
# 按行合并
c = np.append(a, b, axis=0)
print('按行合并后的结果')
print(c)
print('合并后数据维度', c.shape)
# 按列合并
d = np.append(a, b, axis=1)
print('按列合并后的结果')
print(d)
print('合并后数据维度', d.shape)

按行合并后的结果
[[0 1]
 [2 3]
 [0 1]
 [2 3]]
合并后数据维度 (4, 2)
按列合并后的结果
[[0 1 0 1]
 [2 3 2 3]]
合并后数据维度 (2, 4)


In [57]:
# concatenate 沿指定轴连接数组或矩阵

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
print(c)
d = np.concatenate((a, b.T), axis=1)
print(d)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [58]:
# stack 沿指定轴堆叠数组或矩阵：

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.stack((a, b), axis=0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# 1.5 批量处理

* 具体说明：

In [64]:
# ndarray 是 np.array这个方法来创建的一个对象

data_train = np.random.randn(1000,2,3)  # 正态
print(data_train.shape)
np.random.shuffle(data_train)

# 定义批量大小
batch_size = 100

# 进行批处理，每次处理batch_size个数据
for i in range(0, len(data_train), batch_size):
    x_batch_sum = np.sum(data_train[i:i+batch_size])
    print("第{}批次,该批次的数据之和:{}".format(i,x_batch_sum))

(1000, 2, 3)
第0批次,该批次的数据之和:6.83501600459611
第100批次,该批次的数据之和:-9.918939370974012
第200批次,该批次的数据之和:12.0326639852646
第300批次,该批次的数据之和:36.72025627957187
第400批次,该批次的数据之和:44.556853139055605
第500批次,该批次的数据之和:3.234897254003087
第600批次,该批次的数据之和:-21.881643929897283
第700批次,该批次的数据之和:-1.1216447537466063
第800批次,该批次的数据之和:35.14795636932108
第900批次,该批次的数据之和:35.033121418402914


# 1.6 通用函数

* 通用函数（ufunc）

<img src="Screenshot from 2021-02-21 16-25-31.png">

* math与numpy函数的性能比较

In [66]:
import time
import math

x = [i * 0.001 for i in np.arange(1000000)]
start = time.clock()
for i, t in enumerate(x):
    x[i] = math.sin(t)
print ("math.sin:", time.clock() - start )
x = [i * 0.001 for i in np.arange(1000000)]
x = np.array(x)
start = time.clock()
np.sin(x)
print ("numpy.sin:", time.clock() - start )

math.sin: 0.25726899999999997
numpy.sin: 0.013270999999999589


* 循环与向量运算比较

In [68]:
x1 = np.random.rand(1000000)
x2 = np.random.rand(1000000)

## 使用循环计算向量点积
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot += x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n for loop----- Computation time = " + str(1000*(toc - tic)) + "ms")

## 使用numpy函数求点积
tic = time.process_time()
dot = 0
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n verctor version---- Computation time = " + str(1000*(toc - tic)))

dot = 250425.88914897712
 for loop----- Computation time = 569.8321479999997ms
dot = 250425.88914898314
 verctor version---- Computation time = 9.922981000000775


# 1.7 广播机制

1）让所有输入数组都向其中shape最长的数组看齐，不足的部分则通过
在前面加1补齐，如：

a：2×3×2

b：3×2

则b向a看齐，在b的前面加1，变为：1×3×2

2）输出数组的shape是输入数组shape的各个轴上的最大值；

3）如果输入数组的某个轴和输出数组的对应轴的长度相同或者某个轴的长度为1时，这个数组能被用来计算，否则出错；

4）当输入数组的某个轴的长度为1时，沿着此轴运算时都用（或复制）此轴上的第一组值。

In [70]:
# eg:

A = np.arange(0, 40,10).reshape(4, 1)
B = np.arange(0, 3)
print("A矩阵的形状:{},B矩阵的形状:{}".format(A.shape,B.shape))
C=A+B
print("C矩阵的形状:{}".format(C.shape))
print(C)

A矩阵的形状:(4, 1),B矩阵的形状:(3,)
C矩阵的形状:(4, 3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
