In [1]:
import numpy as np

a = np.random.randn(5)
print(a)

[-0.78545741 -0.32901548  0.30162305 -0.44569952  0.35459141]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[-0.78545741 -0.32901548  0.30162305 -0.44569952  0.35459141]


In [4]:
print(a.T.shape)

(5,)


### a.shape == a.T.shape

In [5]:
print(np.dot(a, a.T))

1.1405541189946087


In [6]:
print(np.dot(a.T, a))

1.1405541189946087


### np.dot(a, a.T) == np.dot(a.T, a)

In [10]:
a = np.random.rand(5,1)
print(a.shape)
print(a)

(5, 1)
[[0.95188069]
 [0.02162932]
 [0.31903488]
 [0.84268715]
 [0.93512575]]


In [11]:
print(a.T.shape)
print(a.T)

(1, 5)
[[0.95188069 0.02162932 0.31903488 0.84268715 0.93512575]]


In [12]:
print(np.dot(a, a.T))

[[9.06076852e-01 2.05885328e-02 3.03683138e-01 8.02137630e-01
  8.90128146e-01]
 [2.05885328e-02 4.67827515e-04 6.90050765e-03 1.82267507e-02
  2.02261348e-02]
 [3.03683138e-01 6.90050765e-03 1.01783252e-01 2.68846591e-01
  2.98337728e-01]
 [8.02137630e-01 1.82267507e-02 2.68846591e-01 7.10121638e-01
  7.88018456e-01]
 [8.90128146e-01 2.02261348e-02 2.98337728e-01 7.88018456e-01
  8.74460168e-01]]


* 遇到(5,)这种的向量，使用reshape(5,1)方法