# 2.1 为何选择PyTorch？

PyTorch由4个主要的包组成：


* torch：类似于Numpy的通用数组库，可将张量类型转换为torch.cuda.TensorFloat，并在GPU上进行计算。

* torch.autograd：用于构建计算图形并自动获取梯度的包。

* torch.nn：具有共享层和损失函数的神经网络库。

* torch.optim：具有通用优化算法（如SGD、Adam等）的优化包

# 2.2 安装

In [2]:
# 验证torch安装是否成功

import torch
torch.__version__

'1.7.1'

In [4]:
# 测试是否在使用GPU
# 测试 CUDA

print("Support CUDA ?: ", torch.cuda.is_available())
x = torch.tensor([10.0])
x = x.cuda()
print(x)

y = torch.randn(2, 3)
y = y.cuda()
print(y)

z = x + y
print(z)

# 测试 CUDNN
from torch.backends import cudnn

print("Support cudnn ?: ",cudnn.is_acceptable(x))

Support CUDA ?:  True
tensor([10.], device='cuda:0')
tensor([[ 2.3097,  0.7396,  0.4830],
        [ 0.6227, -0.9433,  0.2236]], device='cuda:0')
tensor([[12.3097, 10.7396, 10.4830],
        [10.6227,  9.0567, 10.2236]], device='cuda:0')
Support cudnn ?:  True


# 2.3 Jupyter Notebook环境配置

# 2.4 Numpy与Tensor

* 最大的区别就是Numpy会把ndarray放在CPU中进行加速运算，而由Torch产生的Tensor会放在GPU中进行加速运算（假设当前环境有GPU）

## 2.4.1 Tensor概述

In [6]:
# 不修改自身 eg:

x = torch.tensor([1,2])
y = torch.tensor([3,4])
z = x.add(y)  # 不带下滑符，不修改数据本身
print(z)
print(x)
x.add_(y)  # 带下滑符，修改数据本身
print(x)

tensor([4, 6])
tensor([1, 2])
tensor([4, 6])


## 2.4.2 创建Tensor

In [7]:
# eg:

# 根据list数据生成Tensor
torch.Tensor([1,2,3,4,5,6])

# 根据指定形状生成Tensor
torch.Tensor(2,3)

# 根据给定的Tensor的形状
t = torch.Tensor([[1,2,3],[4,5,6]])

#查看Tensor的形状
print(t.size())

#shape与size()等价方式
print(t.shape)

#根据已有形状创建Tensor
print(torch.Tensor(t.size()))

torch.Size([2, 3])
torch.Size([2, 3])
tensor([[-5.2810e-24,  4.5629e-41,  9.0200e-28],
        [ 3.0932e-41,  4.4842e-44,  0.0000e+00]])


In [8]:
# 注意torch.Tensor与torch.tensor的几点区别：

t1 = torch.Tensor(1)
t2 = torch.tensor(1)
print("t1的值{},t1的数据类型{}".format(t1,t1.type()))
print("t2的值{},t2的数据类型{}".format(t2,t2.type()))

t1的值tensor([-5.2810e-24]),t1的数据类型torch.FloatTensor
t2的值1,t2的数据类型torch.LongTensor


In [9]:
# eg:

# 生成一个单位矩阵
torch.eye(2,2)

# 自动生成全是0的矩阵
torch.zeros(2,3)

# 根据规则生成数据
torch.linspace(1,10,4)

# 生成满足均匀分布随机数
torch.rand(2,3)

# 生成满足标准分布随机数
torch.randn(2,3)

# 返回所给数据形状相同，值全为0的张量
torch.zeros_like(torch.rand(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## 2.4.3 修改Tensor形状